spring:
  application:
      name:
        product


  datasource:
    url: jdbc:postgresql://localhost:5433/ClothingStore
    username: user
    password: 123

  sql:
    init:
      schema-locations: classpath:db/database.sql
      mode: always


server:
  port: 8081